export enum PipelineStage {
  AUDIO_PREP = 'AUDIO_PREP',
  INSPECTING = 'INSPECTING',
  VAD = 'VAD',
  TRANSCRIBING = 'TRANSCRIBING',
  MERGING = 'MERGING',
  TRANSLATING = 'TRANSLATING',
  EXPORTING = 'EXPORTING',
}
